airbyte_dbt_custom:
  target: prod
  outputs:
    dev:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
      schema: analytics_dev
      threads: 1
      keepalives_idle: 0
    prod:
      type: postgres
      host: localhost
      user: "{{ env_var('DBT_POSTGRES_USER') }}"
      pass: "{{ env_var('DBT_POSTGRES_PASSWORD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
      schema: analytics
      threads: 1
      keepalives_idle: 0