
version: 2

sources:
  - name: pokemon_raw
    database: "{{ env_var('DBT_POSTGRES_DATABASE') }}"
    schema: "{{ env_var('DBT_POSTGRES_DB_SCHEMA') }}"
    tables:
      - name: pokemon
      - name: pokemon_stats
      - name: pokemon_stats_stat

models:
  - name: strong_pokemon
    description: "Pokémon dbt model"
    columns:
      - name: pokemon_name
        tests:
          - unique
          - not_null
